ARG BASE_IMAGE=image_detection_service_deps:latest
FROM ${BASE_IMAGE} AS runtime

WORKDIR /app

ENV PYTHONPATH=/app/api/src:/app/core/src:/app/engine/src

COPY api ./api
COPY core ./core
COPY engine ./engine
COPY alembic ./alembic
COPY alembic.ini ./
RUN mkdir -p logs models

EXPOSE 7987

CMD ["python", "-m", "uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "7987"]
